// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtgdeqynqZrQuD5vIA8eLmtmOC9h8yQU',
    appId: '1:332358236:web:698e1fcacf3d8dab3cbc99',
    messagingSenderId: '332358236',
    projectId: 'ecanteen-362458302092-rakha',
    authDomain: 'ecanteen-362458302092-rakha.firebaseapp.com',
    storageBucket: 'ecanteen-362458302092-rakha.firebasestorage.app',
    measurementId: 'G-1QZQ8JTTV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpomBN20xtYXjmDFtYQQhMM_wDDKC6XXM',
    appId: '1:332358236:android:c5d05838fe35beb63cbc99',
    messagingSenderId: '332358236',
    projectId: 'ecanteen-362458302092-rakha',
    storageBucket: 'ecanteen-362458302092-rakha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0mPStodZYTDVqoGedYgsHI3W9ZeCqCGQ',
    appId: '1:332358236:ios:e68cdda865c4a1fc3cbc99',
    messagingSenderId: '332358236',
    projectId: 'ecanteen-362458302092-rakha',
    storageBucket: 'ecanteen-362458302092-rakha.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0mPStodZYTDVqoGedYgsHI3W9ZeCqCGQ',
    appId: '1:332358236:ios:e68cdda865c4a1fc3cbc99',
    messagingSenderId: '332358236',
    projectId: 'ecanteen-362458302092-rakha',
    storageBucket: 'ecanteen-362458302092-rakha.firebasestorage.app',
    iosBundleId: 'com.example.eCanteen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXtgdeqynqZrQuD5vIA8eLmtmOC9h8yQU',
    appId: '1:332358236:web:8af7785443355c063cbc99',
    messagingSenderId: '332358236',
    projectId: 'ecanteen-362458302092-rakha',
    authDomain: 'ecanteen-362458302092-rakha.firebaseapp.com',
    storageBucket: 'ecanteen-362458302092-rakha.firebasestorage.app',
    measurementId: 'G-H99G9C7XFV',
  );
}
